### ISSUE TITLE
Document that Krun is not multi-user ready

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#233]
```
...
[2016-08-10 15:01:33 DEBUG] Writing out wrapper script to /tmp/krun_wrapper.dash
Traceback (most recent call last):
  File "./krun/krun.py", line 351, in <module>
    main(parser)
  File "./krun/krun.py", line 214, in main
    inner_main(mailer, config, args)
  File "./krun/krun.py", line 311, in inner_main
    sched.run()
  File "/home/vext01/research/warmup_experiment/krun/krun/scheduler.py", line 324, in run
    job.run(self.mailer, self.dry_run)
  File "/home/vext01/research/warmup_experiment/krun/krun/scheduler.py", line 81, in run
    self.parameter, heap_limit_kb, stack_limit_kb)
  File "/home/vext01/research/warmup_experiment/krun/krun/vm_defs.py", line 695, in run_exec
    stack_lim_k, force_dir=force_dir, sync_disks=sync_disks)
  File "/home/vext01/research/warmup_experiment/krun/krun/vm_defs.py", line 369, in _generic_scripting_run_exec
    sync_disks=sync_disks)
  File "/home/vext01/research/warmup_experiment/krun/krun/vm_defs.py", line 196, in _run_exec
    with open(WRAPPER_SCRIPT, "w") as fh:
IOError: [Errno 13] Permission denied: '/tmp/krun_wrapper.dash'
vext01@bencher2:~/research/warmup_experiment$ ls -al /tmp/krun_wrapper.dash 
-rw-r--r-- 1 cfbolz cfbolz 558 Aug 10 12:26 /tmp/krun_wrapper.dash
vext01@bencher2:~/research/warmup_experiment$ id
uid=1003(vext01) gid=1003(vext01) groups=1003(vext01),27(sudo)
```

Although two users shouldn't be benchmarking concurrently on the same system, they could just be developing krun concurrently.

**Comment by ltratt** [comment]
Just a simple lock file would be good enough?

**Comment by ltratt** [comment]
In retrospect, I think this comes under the "document that you shouldn't do that" heading.
