### ISSUE TITLE
AssertionError in PyPy instrumentation code

### ISSUE THREAD

**Issue by snim2** [softdevteam/krun#267]
This error was triggered by a run of the `warmup.krun` config, with `--hardware-reboots` off, and every VM skipped except PyPy. The PyPY VM definition was:

```python
    'PyPy': {
        'vm_def': PyPyVMDef('work/pypy/pypy/goal/pypy-c',
                            env=GCC_ENV, instrument=True),
        'variants': ['default-python'],
        'n_iterations': ITERATIONS_ALL_VMS,
    },
```

and the error was:

```
python2.7 krun/krun.py --no-pstate-check --no-tickless-check warmup.krun
[2016-10-13 22:13:36: INFO] Wait 60 secs to allow system to cool prior to collecting initial temperature readings
[2016-10-13 22:46:18: INFO] Finished 'binarytrees(25)' (default-python variant) under 'PyPy'
[2016-10-13 22:46:18: INFO] 13 executions left in scheduler queue
[2016-10-13 22:48:37: INFO] Estimated completion     : ????-??-?? ??:??:?? (?:??:?? from now)
[2016-10-13 22:48:37: INFO] Next execution is 'fannkuch_redux(200)' (default-python variant) under 'PyPy'
[2016-10-13 22:48:37: INFO] Estimated completion (next execution): ????-??-?? ??:??:?? (?:??:?? from now)
[2016-10-13 22:48:37: INFO] Executions until ETA known: 6
[2016-10-14 00:43:23: INFO] Finished 'fannkuch_redux(200)' (default-python variant) under 'PyPy'
[2016-10-14 00:43:23: INFO] 12 executions left in scheduler queue
[2016-10-14 00:47:47: INFO] Estimated completion     : ????-??-?? ??:??:?? (?:??:?? from now)
[2016-10-14 00:47:47: INFO] Next execution is 'empty(1)' (default-python variant) under 'PyPy'
[2016-10-14 00:47:47: INFO] Estimated completion (next execution): ????-??-?? ??:??:?? (?:??:?? from now)
[2016-10-14 00:47:47: INFO] Executions until ETA known: 5
Traceback (most recent call last):
  File "krun/krun.py", line 346, in <module>
    main(parser)
  File "krun/krun.py", line 209, in main
    inner_main(mailer, config, args)
  File "krun/krun.py", line 306, in inner_main
    sched.run()
  File "/home/snim2/working/warmup_experiment/krun/krun/scheduler.py", line 328, in run
    measurements, instr_data = job.run(self.mailer, self.dry_run)
  File "/home/snim2/working/warmup_experiment/krun/krun/scheduler.py", line 98, in run
    instr_data = vm_def.get_instr_data()
  File "/home/snim2/working/warmup_experiment/krun/krun/vm_defs.py", line 247, in get_instr_data
    return self.parse_instr_stderr_file(fh)
  File "/home/snim2/working/warmup_experiment/krun/krun/vm_defs.py", line 520, in parse_instr_stderr_file
    assert current_node[0] == "root" and len(parent_stack) == 0
AssertionError
Makefile:52: recipe for target 'bench-no-reboots' failed
make: *** [bench-no-reboots] Error 1
```

**Comment by vext01** [comment]
Is it reproducible? Can you put a break point at the crash site and show me the contents of `current_node` and `parent_stack`?

**Comment by snim2** [comment]
Happily, this seems to have disappeared, I think my copy of Krun might have fallen behind master. If I see this again I'll re-raise with some more debug information.
