### ISSUE TITLE
csv_to_krun doesn't output new Krun tags

### ISSUE THREAD

**Issue by ltratt** [softdevteam/krun#270]
I think csv_to_krun needs updating?

```sh
$ bin/csv_to_krun_json -u "`uname -a`" -v HotSpot -l Java dacapo.hotspot.results
$ bin/plot_krun_results dacapo.hotspot.json.bz2
Using matplotlib version 1.4.2 with backend TkAgg
Charting with sliding window size: 200, xlimits: None
Loading: dacapo.hotspot.json.bz2
Traceback (most recent call last):
  File "bin/plot_krun_results", line 1006, in <module>
    options.changepoints)
  File "bin/plot_krun_results", line 713, in get_data_dictionaries
    data_dictionary['cycles_data'][key][machine] = data['core_cycle_counts'][key]
KeyError: 'core_cycle_counts'
```

**Comment by snim2** [comment]
Moving to warmup.
