### ISSUE TITLE
file descriptor exhaustion in no-reboot mode

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#309]
When using fake reboots with the startup experiment:

```
[2017-06-12 15:47:33: INFO] Reboot in preparation for next execution
[2017-06-12 15:47:33: DEBUG] Increment reboot count in manifest
[2017-06-12 15:47:33: DEBUG] Reading status cookie from startup.manifest
[2017-06-12 15:47:33: DEBUG] Reading status cookie from startup.manifest
[2017-06-12 15:47:33: DEBUG] About to execute reboot: 499, expecting 1000 in total.
[2017-06-12 15:47:33: WARNING] SIMULATED: reboot (--hardware-reboots is OFF)
[2017-06-12 15:47:33: DEBUG] Simulated reboot with args: ./krun/krun.py --quick --debug debug startup.krun
PATH SYS: ['/home/kruninit/warmup_experiment/krun', '/usr/local/lib/python27.zip', '/usr/local/lib/python2.7', '/usr/local/lib/
python2.7/plat-openbsd6', '/usr/local/lib/python2.7/lib-tk', '/usr/local/lib/python2.7/lib-old', '/usr/local/lib/python2.7/lib-
dynload', '/usr/local/lib/python2.7/site-packages']
Traceback (most recent call last):
  File "./krun/krun.py", line 18, in <module>
    from krun.mail import Mailer
  File "/home/kruninit/warmup_experiment/krun/krun/mail.py", line 3, in <module>
    from email.mime.text import MIMEText
  File "/usr/local/lib/python2.7/email/mime/text.py", line 10, in <module>
    from email.mime.nonmultipart import MIMENonMultipart
  File "/usr/local/lib/python2.7/email/mime/nonmultipart.py", line 10, in <module>
    from email.mime.base import MIMEBase
  File "/usr/local/lib/python2.7/email/mime/base.py", line 9, in <module>
    from email import message
  File "/usr/local/lib/python2.7/email/message.py", line 16, in <module>
    import email.charset
  File "/usr/local/lib/python2.7/email/charset.py", line 13, in <module>
    import email.base64mime
  File "/usr/local/lib/python2.7/email/base64mime.py", line 40, in <module>
    from email.utils import fix_eols
  File "/usr/local/lib/python2.7/email/utils.py", line 28, in <module>
    import socket
  File "/usr/local/lib/python2.7/socket.py", line 47, in <module>
    import _socket
ImportError: File not found
```

I noticed this always happens on reboot 499, and that the file descriptor limit on the `kruninit` user I was using was 512. I dropped the limit to 100, and it failed the same, but at reboot 87.

My guess is that fake reboots with `os.execv()`do not release their file descriptors.

This is low priority, since it should not affect production mode with reboots.

**Comment by ltratt** [comment]
We suspect that the problem here is that, when forking, Krun inherits things like log file descriptors that it should (but doesn't) close.
