### ISSUE TITLE
Krun does not work in a virtualbox VM.

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#310]
As mentioned via email, I had a hunch krun would not run in a VM as-is. My hunch was right.

```
  File "../krun.py", line 194, in main
    inner_main(mailer, on_first_invocation, config, args)
  File "../krun.py", line 313, in inner_main
    sanity_checks(config, platform)
  File "../krun.py", line 71, in sanity_checks
    platform.sanity_checks()
  File "/home/vext01/krun/krun/platform.py", line 1120, in sanity_checks
    UnixLikePlatform.sanity_checks(self)
  File "/home/vext01/krun/krun/platform.py", line 397, in sanity_checks
    self._sanity_check_user_change()
  File "/home/vext01/krun/krun/platform.py", line 407, in _sanity_check_user_chang
e
    force_dir=PLATFORM_SANITY_CHECK_DIR)
  File "/home/vext01/krun/krun/util.py", line 259, in spawn_sanity_check
    fatal("%s sanity check failed: %s" % (check_name, e.message))
  File "/home/vext01/krun/krun/util.py", line 52, in fatal
    raise FatalKrunError(msg)

Traceback (most recent call last):
  File "../krun.py", line 358, in <module>
    main(parser)
  File "../krun.py", line 203, in main
    raise exn
krun.util.FatalKrunError: UNIX user change sanity check failed: Benchmark returned
 non-zero or emitted invalid JSON.
Exception string: No JSON object could be decoded
return code: 0
stdout:
--------------------------------------------------
arch pctr version >=2 is required! got 0

--------------------------------------------------
```

This is a failing sanity check. We use the `CPUID` x86 instruction to ask what performance counters are available. The ones we need are level 2, but the VM returns 0, which probably means none.

I may be able hack around this, as somewhere else in Krun, we are already checking for a virtualised host.

This blocks the artefact.

**Comment by vext01** [comment]
Our problem is: https://github.com/softdevteam/krun/blob/master/libkrun/libkruntime.c#L316

libkrun does not know that we may not have any performance counters.
