### ISSUE TITLE
Python Iteration Runner Broken

### ISSUE THREAD

**Issue by vext01** [softdevteam/krun#383]
```
[iterations_runner.py] iteration 1/1
Traceback (most recent call last):
  File "/home/kruninit/warmup_experiment/krun/iterations_runners/iterations_runner.py", line 166, in <module>
    sys.stdout.write("%s\n" % json.dumps(js))
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: array('L', [96252L]) is not JSON serializable
```

The typed array cannot be encoded to JSON it seems.

**Comment by ltratt** [comment]
This is my fault for not testing properly. Mea culpa!
